export const PRIVACY_EFFECTIVE = 'June 7, 2025';
export const PRIVACY_UPDATED = 'August 2, 2026';

export interface PrivacySection {
  heading: string;
  paragraphs: string[];
  list?: string[];
}

export const PRIVACY_INTRO = [
  'Edora ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use the Edora mobile application and related services.',
  'Age requirement: Edora is intended for users aged 13 and older. By using this app, you confirm that you are at least 13 years of age. Users in India who are under 18 are subject to additional protections and a parental consent flow described in Section 7a below.',
];

export const PRIVACY_SECTIONS: PrivacySection[] = [
  {
    heading: '1. Information We Collect',
    paragraphs: [
      'Account information — When you register, we collect your email address and display name. You may also sign in with Google or Microsoft, in which case we receive your name, email, and profile picture from that provider. We never receive or store your Google or Microsoft password.',
      'Google Classroom / Gmail / Calendar / Drive connector (teachers) — If you connect a Google account to enable classroom, calendar, or email features, we request access only to the specific scopes each feature needs: Classroom rosters and coursework (read/manage coursework you create), Calendar (to create/update study events and Meet links), Gmail (send-only — we can send email as you but cannot read your inbox), and Drive (limited to files Edora itself creates, not your full Drive). Access and refresh tokens are encrypted at rest and are used only to operate the feature you enabled; you can disconnect at any time from Account Settings, which deletes the stored tokens immediately.',
      'User-generated content — Notes, study materials, chat messages, scanned documents, and other content you create within the app.',
      'Device & usage data — Device type, operating system version, app version, and feature usage patterns (collected anonymously via PostHog analytics).',
      'Camera & media — Only when you explicitly use the Scanner feature. Images are processed for text recognition and are not stored on our servers beyond what is needed to display results.',
      'Push notification token — A device token used solely to deliver study reminders and notifications you have enabled.',
      'Crash & error data — Anonymised error reports and stack traces collected via Sentry to help us fix bugs.',
      "Voice & microphone data — Only when you use Voice Study or Voice Quiz features. Your speech is transcribed (using your device's speech recognition or, for regional languages, Google Cloud Speech-to-Text) and the resulting text transcript is stored as part of your tutoring conversation history so you can review past sessions. We do not store raw audio recordings.",
    ],
  },
  {
    heading: '2. How We Use Your Information',
    paragraphs: [],
    list: [
      'Provide, personalise, and improve the Edora app and its features',
      'Authenticate your identity and maintain your account',
      'Send study reminders and notifications you request',
      'Generate AI-powered responses using the Gemini API and ElevenLabs text-to-speech',
      'Diagnose technical issues and improve app stability',
      'Comply with legal obligations',
    ],
  },
  {
    heading: '2a. Artificial Intelligence (AI) Features',
    paragraphs: [
      'Edora uses AI-generated content throughout the app, generated using a combination of AI providers (Google Gemini, Groq, and — for a small number of non-latency-critical narrative summaries such as weekly parent reports and exam-readiness assessments — NVIDIA NIM). This includes:',
    ],
    list: [
      'AI Tutoring — Novo AI generates personalised explanations, questions, and feedback in real time.',
      'Quiz & Tournament Questions — Questions are generated by AI and may vary in accuracy. They are designed for educational practice only.',
      'Boss Challenges & Streak Tasks — Daily problems and challenge content are AI-generated.',
      'AI-graded Answers — Open-ended answers are evaluated by AI; scores are indicative, not official assessments.',
      "Text-to-Speech — Novo's voice (powered by ElevenLabs) is AI-synthesised.",
      'Study Packs & Summaries — Flashcards, quiz questions, and summaries generated from uploaded documents are AI-generated.',
      'Translation — Regional-language question translation and in-chat translation are powered by Google Cloud Translation.',
    ],
  },
  {
    heading: '3. Third-Party Services',
    paragraphs: [
      'We use the following third-party services to operate Edora. Each has its own privacy policy:',
    ],
    list: [
      'Supabase — Database, authentication, and backend infrastructure.',
      'Google Firebase — Push notification delivery (FCM) and analytics.',
      'Microsoft (Azure AD) — Optional Microsoft sign-in.',
      'Google Classroom, Calendar, Gmail, Drive APIs — Optional teacher-facing connector described in Section 1, scoped to the specific feature you enable.',
      'Google Gemini API — AI-powered study assistance.',
      'Groq — AI inference for tutoring and chat responses.',
      'NVIDIA (NIM) — AI inference for a small set of non-latency-critical narrative summaries (e.g. weekly parent reports).',
      'ElevenLabs — Text-to-speech audio generation.',
      'Google Cloud Vision — Optical character recognition for the Scanner feature.',
      'Google Cloud Speech-to-Text — Voice transcription for regional-language Voice Study/Quiz.',
      'Google Cloud Translation — Regional-language question and chat translation.',
      'Razorpay — Payment processing for Edora Pro subscriptions. Razorpay receives the payment details you provide at checkout; Edora does not store your card or UPI details.',
      'Sentry — Crash reporting and error monitoring.',
      'PostHog — Anonymous usage analytics.',
    ],
  },
  {
    heading: '4. Data Sharing',
    paragraphs: [
      'We do not sell, rent, or trade your personal information to third parties. We may share data only in these limited circumstances:',
    ],
    list: [
      'With the third-party service providers listed above, solely to operate the app',
      'If required by law, court order, or governmental authority',
      'To protect the rights, property, or safety of Edora, our users, or the public',
    ],
  },
  {
    heading: '5. Data Retention & Deletion',
    paragraphs: [
      'We retain your account data for as long as your account is active. You can export or delete your data directly within the app at any time from the Data Rights screen:',
      '→ Open Edora → Profile tab → Account Settings → Data Rights',
      'From this screen you can download a copy of your data (profile, study history, flashcards, chat history) as a JSON export, or request account deletion. Account deletion permanently removes all your data from our systems within 30 days. You may also request either action by contacting us at the email below.',
    ],
  },
  {
    heading: '6. Data Security',
    paragraphs: [
      'All data is encrypted in transit using TLS. Data at rest is stored on Supabase infrastructure with row-level security policies that ensure users can only access their own data.',
    ],
  },
  {
    heading: "7. Children's Privacy (COPPA Compliance)",
    paragraphs: [
      'Edora is intended for users aged 13 and older. We do not knowingly collect personal information from children under 13. Users must confirm they are 13 or older during account setup.',
      'If you are a parent or guardian and believe your child under 13 has created an account, please contact us immediately at support@edora.app and we will delete the account and all associated data within 30 days.',
      'Edora does not target children under 13 and does not permit users under 13 to create accounts.',
    ],
  },
  {
    heading: '7a. India — Digital Personal Data Protection Act, 2023 (DPDP Act)',
    paragraphs: [
      'For users in India, Edora processes personal data as a Data Fiduciary under the DPDP Act, 2023, in addition to the protections described elsewhere in this policy.',
      'Age verification & parental consent — During sign-up, we ask whether you are 18 or older. If you indicate you are under 18, Edora treats you as a "Child" under the DPDP Act: we apply enhanced data protections and request verifiable consent from a parent or guardian before continuing to process your data, consistent with Section 9 of the Act. You (or your parent/guardian) can review or withdraw this consent at any time from the Data Rights screen described in Section 5.',
      'Purpose limitation — We collect and process only the personal data described in Section 1, strictly for the purposes described in Section 2, and do not use it for unrelated purposes without fresh consent.',
      'Data Principal rights (Sections 11–14) — As a Data Principal, you have the right to: obtain a summary of your personal data and the processing activities we carry out on it; request correction, completion, or erasure of your personal data; nominate another individual to exercise your rights in the event of death or incapacity; and file a grievance with us, and thereafter with the Data Protection Board of India if unresolved. You can exercise the access, correction, and erasure rights directly and immediately from the in-app Data Rights screen (Profile → Account Settings → Data Rights).',
      'Consent withdrawal — You may withdraw consent at any time from the Data Rights screen or by emailing our Grievance/DPO contact below. Withdrawing consent does not affect the lawfulness of processing carried out before withdrawal, and may mean some features become unavailable.',
      'Data breach notification — In the event of a personal data breach, we will notify the Data Protection Board of India and affected users as required under the Act.',
      'Grievance Officer / DPO — For any DPDP-related query, consent withdrawal, or grievance, contact our Data Protection Officer at dpo@edora.app. We aim to acknowledge grievances within 7 days and resolve them within 30 days.',
    ],
  },
  {
    heading: '8. Your Rights',
    paragraphs: ['Depending on your location, you may have the right to:'],
    list: [
      'Access the personal data we hold about you',
      'Correct inaccurate data',
      'Request deletion of your data',
      'Withdraw consent at any time',
      'Lodge a complaint with a data protection authority — in India, the Data Protection Board of India; elsewhere, your local data protection authority',
    ],
  },
  {
    heading: '9. Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time. We will notify you of significant changes by posting the new policy in the app or via email. The "Last updated" date at the top of this page reflects the most recent revision.',
    ],
  },
  {
    heading: '10. Contact Us',
    paragraphs: [
      'If you have any questions or concerns about this Privacy Policy, please contact us at:',
      'General support: support@edora.app',
      'DPDP grievances / Data Protection Officer (India): dpo@edora.app',
    ],
  },
];
